version: "3.3"
services:
  spark-worker-21:
    image: docker.io/bitnami/spark:3.4.1
    container_name: sp_work_21
    network_mode: "host"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=192.168.11.106
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_URL=spark://192.168.11.106:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:   
       - ./scala:/opt/spark-apps
       - ./data:/opt/spark-data
       - /etc/timezone:/etc/timezone 
       - /etc/localtime:/etc/localtime 
       - /etc/passwd:/etc/passwd 
       - /etc/group:/etc/group
  spark-worker-22:
    image: docker.io/bitnami/spark:3.4.1
    container_name: sp_work_22
    network_mode: "host"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=192.168.11.106
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_URL=spark://192.168.11.106:7077
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
       - /etc/timezone:/etc/timezone 
       - /etc/localtime:/etc/localtime 
       - /etc/passwd:/etc/passwd 
       - /etc/group:/etc/group
       - /home/thomas:/home/thomas